# Generated by Django 5.2.7 on 2025-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.CharField(max_length=255)),
            ],
        ),
    ]
